@baseUrl = http://localhost:8000/api

###
# 🧾 Hae kaikki labratulokset
GET {{baseUrl}}/labtestresults
Accept: application/json


###
# 🔍 Hae yksi tulos ID:n perusteella
# Vaihda ID halutuksi (esim. 1)
GET {{baseUrl}}/labtestresults/2033
Accept: application/json

###
# 🔎 Hae kaikki labratulokset tietylle henkilölle
GET http://localhost:8000/api/labtestresults/person/TEST123
Accept: application/json

###
# 🔎 Hae henkilön tietty tulos ID:llä
GET http://localhost:8000/api/labtestresults/person/TEST123/id/2033
Accept: application/json

###
# 🔎 Hae henkilön kaikki tulokset aikaväliltä
# Päivämäärät annetaan muodossa YYYY-MM-DD tai YYYY-MM-DDTHH:MM:SS
GET http://localhost:8000/api/labtestresults/person/TEST123/dates/2025-01-01/2025-12-31
Accept: application/json

###
# 🔎 Hae henkilön tulokset analyysinimen osalla
# Esim. hakee kaikki, joissa AnalysisName sisältää "TS"
GET http://localhost:8000/api/labtestresults/person/TEST123/analysis/Kol
Accept: application/json



###
# 🔎 Hae henkilön tulokset analyysinimen osalla
# Esim. hakee kaikki, joissa AnalysisName sisältää "TS"
GET http://localhost:8000/api/labtestresults/person/170366/analysis/TSH
Accept: application/json

###
# ➕ Lisää uusi tulos (POST)
# Huom: toimii vain jos tietokanta sallii INSERT-toiminnon.
POST {{baseUrl}}/labtestresults
Content-Type: application/json
Accept: application/json

{
  "PersonID": "TEST123",
  "SampleDate": "2025-10-11",
  "CombinedName": "TESTIGlukoosi, verinäyte",
  "AnalysisName": "TESTIGlukoosi",
  "AnalysisShortName": "TESTGlu",
  "AnalysisCode": "TESTGLU",
  "Result": "5.3",
  "MinimumValue": "4.0",
  "MaximumValue": "6.0",
  "ValueReference": "Kaikki",
  "Unit": "mmol/l",
  "Cost": 12.50,
  "CompanyUnitName": "LabTest Oy",
  "AdditionalInfo": "TESTI paastotesti",
  "AdditionalText": "TESTI Aamupaasto 10h",
  "ResultAddedDate": "2025-10-11 09:00:00",
  "ToMapDate": "2025-10-11 09:00:00"
}


###
# ✏️ Päivitä olemassa oleva tulos (PUT)
# Vaihda ID oikeaksi olemassa olevaksi riviksi
PUT {{baseUrl}}/labtestresults/2033
Content-Type: application/json
Accept: application/json

{
  "Result": "5.6",
  "AdditionalText": "Päivitetty testimielessä"
}


###
# 🗑️ Poista tulos (DELETE)
# Vaihda ID oikeaksi
#DELETE {{baseUrl}}/labtestresults/2032
#Accept: application/json
